listen: ":8080"

# check these headers for client ip.
# useful when behind reverse-proxy.
# be careful that these headers may come from untrusted source
# and this service do NOT apply any check for the source.
real_ip_header: [ "X-Forwarded-For", "X-Real-Ip" ] # in order of perference

download:
  dir: "/data/" # save db under /data/
  reload_gap: 336h # refresh db every 336h
  asn_url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-ASN.mmdb"
  city_url: "https://github.com/P3TERX/GeoLite.mmdb/raw/download/GeoLite2-City.mmdb"

log:
  level: INFO # DEBUG INFO WARN ERROR
  # file to save access log
  # special value 'stdout' will output access log to stdout
  # use empty value to disable access log 
  access: "stdout"
  output:
  - stdout # special value 'stdout'
  - ./log # also save log to file './log'
